#!/bin/sh

MVN=mvn

function run_mvn() {
  PROFILES=$1
  PHASES=$2
  SWITCH=$3
  if [ -z "${SWITCH}" ]; then
    ${MVN} -U -P${PROFILES} ${PHASES}
  else
    ${MVN} -U -P${PROFILES} ${PHASES} -D${SWITCH}
  fi
}

case "$1" in
  clean)
    run_mvn integration,distribution,apache,jldap,opendj,unboundid clean
    ;;
  package)
    run_mvn distribution,apache,jldap,opendj,unboundid package
    ;;
  verify)
    run_mvn distribution,apache,jldap,opendj,unboundid verify
    ;;
  install)
    run_mvn distribution,apache,jldap,opendj,unboundid install
    ;;
  deploy)
    LOCAL_REPO=${2}
    if [ -z "${LOCAL_REPO}" ]; then
      echo "USAGE: `basename $0` deploy <repo-directory>"
      exit 1
    fi
    run_mvn apache,jldap,opendj,unboundid clean
    run_mvn apache,jldap,opendj,unboundid deploy "altDeploymentRepository=snapshot::default::file://${LOCAL_REPO}"
    ;;
  bundle-create)
    run_mvn distribution,apache,jldap,opendj,unboundid repository:bundle-create sign=true
    ;;
  *)
    if [ -n "$1" ]; then
      echo "Invalid command"
    fi
    echo "USAGE: `basename $0` clean|package|verify|install|deploy|bundle-create"
esac
