#!/bin/bash

## SCRIPT VARIABLES
# PROFILE_CLASS: java class to profile
# THREAD_COUNT: number of threads to execute operations
# THREAD_SLEEP: time in milliseconds to wait between submitting operations, ignored if ITERATIONS is used
# ITERATIONS: number of operations to invoke, no value means execute indefinitely
# USE_YOURKIT: whether to set MAVEN_OPTS for the yourkit profiler, default is for jconsole

docker compose -f profile/docker-compose.yml down && \
  docker network prune -f && \
  docker compose -f profile/docker-compose.yml pull && \
  docker compose -f profile/docker-compose.yml up --build --attach ldaptive
