#!/bin/bash

set -e

FUZZ_VERSION=0.24.0
# maximum time in seconds for each fuzzer
MAX_FUZZ_TIME=30

mvn -pl fuzz -Pfuzz -Dmaven.javadoc.skip=true clean package
tar xzf fuzz/jazzer-linux-${FUZZ_VERSION}.tar.gz -C fuzz/target

for i in fuzz/target/lib/*.jar; do
  CLASSPATH=$CLASSPATH:$i
done

# recommended java options
export JAVA_OPTS="-XX:-OmitStackTraceInFastThrow -XX:+UseParallelGC -XX:+CriticalJNINatives -XX:+EnableDynamicAgentLoading"

# jazzer can't generate input for these classes
#"org.ldaptive.handler.CompareValueHandler::accept"
#"org.ldaptive.handler.CompleteHandler::execute"
#"org.ldaptive.handler.ExceptionHandler::accept"
#"org.ldaptive.handler.ExtendedValueHandler::accept"
#"org.ldaptive.handler.IntermediateResponseHandler::accept"
#"org.ldaptive.handler.LdapEntryHandler::apply"
#"org.ldaptive.handler.ReferralHandler::accept"
#"org.ldaptive.handler.ReferralResultHandler::apply"
#"org.ldaptive.handler.RequestHandler::accept"
#"org.ldaptive.handler.ResponseControlHandler::accept"
#"org.ldaptive.handler.ResultHandler::accept"
#"org.ldaptive.handler.ResultPredicate::testAndThrow"
#"org.ldaptive.handler.SearchReferenceHandler::apply"
#"org.ldaptive.handler.SearchResultHandler::apply"
#"org.ldaptive.handler.UnsolicitedNotificationHandler::accept"
#"org.ldaptive.io.LdifWriter::write"
#"org.ldaptive.io.LdifReader::read"
#"org.ldaptive.url.UrlFormatter::format"

AUTO_FUZZ=(
"org.ldaptive.AddResponse::new;java.lang.IllegalArgumentException"
"org.ldaptive.BindResponse::new;java.lang.IllegalArgumentException"
"org.ldaptive.CompareResponse::new;java.lang.IllegalArgumentException"
"org.ldaptive.DeleteResponse::new;java.lang.IllegalArgumentException"
"org.ldaptive.FilterTemplate::format;java.lang.IllegalStateException"
"org.ldaptive.LdapAttribute::new;java.lang.IllegalArgumentException"
"org.ldaptive.LdapEntry::new;java.lang.IllegalArgumentException"
"org.ldaptive.LdapURL::new;java.lang.IllegalArgumentException"
"org.ldaptive.ModifyDnResponse::new;java.lang.IllegalArgumentException"
"org.ldaptive.ModifyResponse::new;java.lang.IllegalArgumentException"
"org.ldaptive.Request::encode;java.lang.IllegalArgumentException,java.lang.IllegalStateException"
"org.ldaptive.SearchResponse::new;java.lang.IllegalArgumentException"
"org.ldaptive.SearchResultReference::new;java.lang.IllegalArgumentException"
"org.ldaptive.ad.GlobalIdentifier::toBytes;java.lang.IllegalArgumentException"
"org.ldaptive.ad.GlobalIdentifier::toString;java.lang.IllegalArgumentException"
"org.ldaptive.ad.SecurityIdentifier::toBytes;java.lang.IllegalArgumentException"
"org.ldaptive.ad.SecurityIdentifier::toString;java.lang.IllegalArgumentException"
"org.ldaptive.asn1.DERParser::parse;java.lang.IllegalArgumentException"
"org.ldaptive.auth.Authenticator::authenticate;java.lang.IllegalArgumentException,java.lang.IllegalStateException"
"org.ldaptive.auth.EntryResolver::resolve;java.lang.IllegalArgumentException"
"org.ldaptive.auth.DnResolver::resolve;java.lang.IllegalArgumentException,java.lang.IllegalStateException"
"org.ldaptive.control.RequestControl::encode;java.lang.IllegalArgumentException,java.lang.IllegalStateException"
"org.ldaptive.control.ResponseControl::decode;java.lang.IllegalArgumentException,java.lang.IllegalStateException"
"org.ldaptive.dn.AttributeValueEscaper::escape"
"org.ldaptive.dn.DnParser::parse;java.lang.IllegalArgumentException"
"org.ldaptive.dn.RDnNormalizer::normalize;java.lang.IllegalArgumentException,java.lang.ClassCastException"
"org.ldaptive.dns.DNSResolver::resolve;java.lang.IllegalArgumentException"
"org.ldaptive.extended.ExtendedResponse::new;java.lang.IllegalArgumentException"
"org.ldaptive.extended.IntermediateResponse::new;java.lang.IllegalArgumentException"
"org.ldaptive.filter.Filter::getEncoder;java.lang.IllegalArgumentException,java.lang.IllegalStateException"
"org.ldaptive.filter.FilterFunction::parse;java.lang.IllegalArgumentException"
"org.ldaptive.io.Hex::encode"
"org.ldaptive.io.Hex::decode;java.lang.IllegalArgumentException"
"org.ldaptive.jaas.RoleResolver::search;java.lang.IllegalArgumentException,java.lang.IllegalStateException"
"org.ldaptive.pool.ConnectionPool::initialize;java.lang.IllegalStateException"
"org.ldaptive.transport.ResponseParser::parse;java.lang.IllegalArgumentException"
"org.ldaptive.transcode.ValueTranscoder::decodeStringValue;java.lang.IllegalArgumentException"
"org.ldaptive.transcode.ValueTranscoder::decodeBinaryValue;java.lang.IllegalArgumentException"
"org.ldaptive.url.Url::new;java.lang.IllegalArgumentException"
"org.ldaptive.url.UrlParser::parse;java.lang.IllegalArgumentException"
"javax.security.auth.spi.LoginModule::login"
"javax.security.auth.spi.LoginModule::commit"
"javax.security.auth.spi.LoginModule::abort"
"javax.security.auth.spi.LoginModule::logout"
)

# see https://llvm.org/docs/LibFuzzer.html#options for command line options
for FUZZ in ${AUTO_FUZZ[@]}; do
  FUZZ_ARR=(${FUZZ//;/ })
  echo "-------------------------"
  echo "  begin autofuzz: ${FUZZ_ARR[0]}  "
  echo "-------------------------"
  fuzz/target/jazzer -max_total_time="$MAX_FUZZ_TIME" -timeout=60 --cp="$CLASSPATH" --reproducer_path=fuzz/target --autofuzz="${FUZZ_ARR[0]}" --autofuzz_ignore="${FUZZ_ARR[1]}" --coverage_report="fuzz/target/jazzer_report_${FUZZ_ARR[0]}.txt"
done
