#!/bin/bash

# Install patch binary
if ! command -v patch &> /dev/null
then
  if command -v apt-get &> /dev/null
  then
    apt-get update && apt-get install -y patch
  elif command -v yum &> /dev/null
  then
    yum install -y patch
  else
    echo "patch could not be installed"
    exit 1
  fi
fi

# execute maven in docker
mvn install -Dmaven.javadoc.skip=true -B -V
ret_code=$?
if [ $ret_code != 0 ]; then
  echo "Maven install failed with error code ${ret_code}"
  exit $ret_code
fi

# execute snapshot deploy in docker
.travis/deploy-snapshot
ret_code=$?
if [ $ret_code != 0 ]; then
  echo "Deploy snapshot failed with error code ${ret_code}"
  exit $ret_code
fi

exit
