#!/bin/bash

SSL_HOST=`echo ${HOST} |sed 's/389/636/'`
MVN_OPTS="-pl integration -Pintegration clean verify"

mvn -Dmaven.javadoc.skip=true -B -V -e \
  -DldapTestHost=ldap://${HOST} \
  -DldapSslTestHost=ldaps://${SSL_HOST} \
  -DldapBaseDn="${BASE_DN}" \
  -DldapBindDn="${BIND_DN}" \
  -DldapBindCredential="${BIND_CREDENTIAL}" \
  -DldapTestGroup="${TEST_GROUP}" \
  -DuseShaded="${USE_SHADED}" \
  ${MVN_OPTS}
