#!/bin/bash

set -e

HOST="ldap-test:389"
SSL_HOST=`echo ${HOST} |sed 's/389/636/'`
BASE_DN="ou=test,dc=vt,dc=edu"
BIND_DN="uid=1,ou=test,dc=vt,dc=edu"
BIND_CREDENTIAL="VKSxXwlU7YssGl1foLMH2mGMWkifbODb1djfJ4t2"

if [ -z "${TEST_GROUP}" ]; then
  TEST_GROUP="core"
fi

if [ -z "${USE_SHADED}" ]; then
  USE_SHADED="false"
fi

if [ -z "${JDK}" ]; then
  JDK="11"
fi

mvn -pl integration -Pintegration clean
if [ ! -d "integration/target" ]; then
  mkdir integration/target
fi
DOCKER_FILE="integration/target/Dockerfile-jdk${JDK}"
sed "s/__JDK__/${JDK}/" "integration/Dockerfile" >"$DOCKER_FILE"
COMPOSE_FILE="integration/target/docker-compose-jdk${JDK}.yml"
sed "s/__JDK__/${JDK}/" "integration/docker-compose.yml" >"$COMPOSE_FILE"

mvn -Dmaven.javadoc.skip=true -B -V -e \
  -DldapTestHost=ldap://${HOST} \
  -DldapSslTestHost=ldaps://${SSL_HOST} \
  -DldapBaseDn="${BASE_DN}" \
  -DldapBindDn="${BIND_DN}" \
  -DldapBindCredential="${BIND_CREDENTIAL}" \
  -DldapTestGroup="${TEST_GROUP}" \
  -DuseShaded="${USE_SHADED}" \
  -pl integration -Pshade,integration package

echo "================================"
echo "Begin integration tests"
echo "TEST_GROUP: ${TEST_GROUP}"
echo "USE_SHADED: ${USE_SHADED}"
echo "JDK: ${JDK}"
echo "================================"

docker compose -f ${COMPOSE_FILE} down && \
  docker network prune -f && \
  docker compose -f ${COMPOSE_FILE} pull && \
  BIND_DN="${BIND_DN}" BIND_CREDENTIAL="${BIND_CREDENTIAL}" JDK="${JDK}" docker compose -f ${COMPOSE_FILE} up --build --abort-on-container-exit --attach ldaptive
